services:
  # 2. SERVIÇO DA APLICAÇÃO (Next.js)
  web:
    build: .
    container_name: patrimonio_web
    restart: always # Se o PC reiniciar, o sistema liga sozinho
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
 